### ISSUE TITLE
bug in wasserstein_distance function?

### ISSUE THREAD

**Issue by xinyue96** [aywagner/DIPOLE#2]
It's a bit weird that the cost computed by the WassersteinDistance class in pers.py doesn't equal to the cost computed by the gudhi function. 
Should the following lines of code in the WasserteinDistance class:
        if np.any(is_unpaired_1):
            unpaired_1_idx = matching[is_unpaired_1, 0]
            cost = cost + torch.sum(torch.pow(dgm1[unpaired_1_idx, 1] - dgm1[unpaired_1_idx, 0], self.p))
        is_unpaired_2 = (matching[:, 1] == -1)
        if np.any(is_unpaired_2):
            unpaired_2_idx = matching[is_unpaired_2, 1]
            cost = cost + torch.sum(torch.pow(dgm2[unpaired_2_idx, 1] - dgm1[unpaired_2_idx, 0], self.p))

be replaced by:
if np.any(is_unpaired_1):
    unpaired_1_idx = matching[np.where(matching[:, 1] == -1),0]
    cost = cost + torch.sum(torch.pow(dgm1[unpaired_1_idx, 1] - dgm1[unpaired_1_idx, 0], self.p))
is_unpaired_2 = (matching[:, 1] == -1)
if np.any(is_unpaired_2):
    unpaired_2_idx = matching[np.where(matching[:, 0] == -1),1]
    cost = cost + torch.sum(torch.pow(dgm2[unpaired_2_idx, 1] - dgm2[unpaired_2_idx, 0], self.p))

**Comment by aywagner** [comment]
Thank you for pointing this out! 

The last line of the code snippet you reference should indeed have dgm1 replaced with dgm2 as you suggest. 

However, I don't think the other change in your suggested revision will fix the bug because the problem is how is_unpaired_1 and is_unpaired_2 are defined. Currently, is_unpaired_1 = (matching[:, 0] == -1) but this array will be true for elements of dgm2 that are matched to the diagonal, so changing it to is_unpaired_1 = (matching[:, 1] == -1) and an analogous change for is_unpaired_2 should fix the bug.
